### ISSUE TITLE
Some Browsers can no longer view the tumblrs

### ISSUE THREAD

**Issue by The1nstructor** [fapinstructor/fapinstructor#16]
A workaround is to open the tumblrs in seperate tabs and wohey! Everything works as expected. At least on Windows 10 under Firefox and under MacOS on Tor.

I'm not enough into it to pinpoint the origin of this problem, sorry.

**Comment by ArtisticMenase** [comment]
I have a feeling this is down to an issue with accessing NSFW blogs without some sort of age verification cookie  from logging in. 

I can't be certain but generally this issue is fixed for me by just logging in to tumblr on a different tab in the same browser session, which is what makes me suspicious. Will take a deeper look this weekend.

**Comment by The1nstructor** [comment]
Maybe one could get this cookie before starting the game where currently only the `start`-button is displayed. Just an idea, I'm not enough into cookies :laughing:

**Comment by ArtisticMenase** [comment]
So I actually took a look and it seems like it's done through request headers (inspecting cookies didn't reveal anything obviously to do with nsfw but I'll have more time to do investigate properly tomorrow) which is a problem for us.

Fetch-jsonp doesn't support custom request headers, so even if we can send custom headers to get nsfw without being logged in, our fetchjsonp method won't let us use it. I can think of 2 solutions we can do and then a lazy option: 

- We change from fetchjsonp to something that  supports request headers 

- We force log in before game start of there are tumblr blogs 

- We just put a warning saying log in to tumblr or it ain't gonna work on the start page.

**Comment by h3110D** [comment]
Updating Tumblr API to v2 should resolve this. At least according to my tests.
I've got the code ready (#99), it just needs an API key.

**Comment by The1nstructor** [comment]
#89 issue is no longer valid.
Instead now #98 is used.
