### ISSUE TITLE
only tumblr seems to work

### ISSUE THREAD

**Issue by edginggames** [fapinstructor/fapinstructor#36]
I was using the app on Android mobile Chrome and only the tumblr feeds worked.  I tested this by taking out all the tumblr feeds and just had a comma separated list of reddit feeds.  The app just spun and didn't show any images/vids.

**Comment by The1nstructor** [comment]
I almost experienced the same on iOS mobile Chrome:

Tumblrs seemed to work with the well known workaround from #... 
but I did not get any sound output so no metronome and else. 

Did you expire the same @...

**Comment by edginggames** [comment]
I will open reddit and see if that helps

**Comment by edginggames** [comment]
logged into reddit and still only tumblr works :(

**Comment by edginggames** [comment]
That would explain the problem for sure!

**Comment by The1nstructor** [comment]
This has been solved by #54
