### ISSUE TITLE
Can't resolve '@babel/runtime/core-js/map' in '...\fapinstructor\node_modules\material-ui\styles'

### ISSUE THREAD

**Issue by LenAnderson** [fapinstructor/fapinstructor#53]
When trying to run fapinstructor as instructed in the readme this is what I get after `npm start`:

    Failed to compile
      ./node_modules/material-ui/styles/withStyles.js
      Module not found: Can't resolve '@babel/runtime/core-js/map' in '...\fapinstructor\node_modules\material-ui\styles'
    This error occurred during the build time and cannot be dismissed.

**Comment by The1nstructor** [comment]
Hey there,

Maybe you have to try and update/fix it by hand.
I had to do this with _@ajv_ too in the very beginning. When I set up the dev-env for the first time 😆 

Maybe try sth like:
  -  `npm install @babel/runtime/core-js/map` 
    or 
 -   `npm update @babel/runtime/core-js/map` 😉

**Comment by LenAnderson** [comment]
I don't know if that's the right way to do it, but by adding `"@babel/runtime": "7.0.0-beta.55"` as a dependency in `package.json` (before running install) I was able to get it to run.

output of `yarn`

    yarn install v1.9.4
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    [1/4] Resolving packages...
    warning material-ui-icons@1.0.0-beta.36: Use @material-ui/icons instead
    [2/4] Fetching packages...
    info fsevents@1.1.3: The platform "win32" is incompatible with this module.
    info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 65.44s.


output of `npm update`

    npm WARN deprecated material-ui@1.0.0-beta.47: You can now upgrade to @material-ui/core
    
    > husky@0.14.3 uninstall ...\husky
    > node ./bin/uninstall.js
    
    husky
    uninstalling Git hooks
    done
    
    npm WARN rm not removing ...\.bin\jest.cmd as it wasn't installed by ...\jest
    npm WARN rm not removing ...\.bin\jest as it wasn't installed by ...\jest
    npm WARN rm not removing ...\.bin\uglifyjs.cmd as it wasn't installed by ...\uglify-js
    npm WARN rm not removing ...\.bin\uglifyjs as it wasn't installed by ...\uglify-js
    npm WARN rm not removing ...\.bin\browserslist.cmd as it wasn't installed by ...\browserslist
    npm WARN rm not removing ...\.bin\browserslist as it wasn't installed by ...\browserslist
    
    > husky@0.14.3 install ...\husky
    > node ./bin/install.js
    
    husky
    setting up Git hooks
    done
    
    
    > jss@9.8.7 postinstall ...\jss
    > node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"
    
    Love JSS? You can now support us on open collective:
     > https://opencollective.com/jss/donate
    
    > uglifyjs-webpack-plugin@0.4.6 postinstall ...\uglifyjs-webpack-plugin
    > node lib/post_install.js
    
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
    
    + lodash@4.17.11
    + js-base64@2.4.9
    + prettier@1.14.3
    + material-ui@1.0.0-beta.47
    + lint-staged@7.3.0
    + react@16.5.2
    + moment@2.22.2
    + react-router-dom@4.3.1
    + raven-js@3.27.0
    + react-dom@16.5.2
    added 338 packages, removed 249 packages and updated 1140 packages in 158.329s

**Comment by The1nstructor** [comment]
👍

**Comment by The1nstructor** [comment]
I think due to you made it running, we can safely close this issue 😉
