### ISSUE TITLE
Post Orgasm Torture doesn't always work

### ISSUE THREAD

**Issue by thefapinstructor** [fapinstructor/fapinstructor#6]
The post orgasm torture doesn't always work (some aspects not refreshing between testing sessions probably)

**Comment by The1nstructor** [comment]
The problem was the stored `store.config.maximumOrgasms`

It was not accessed via parseInt on the GamePage and thereby did not work properly. #42 will fix this.

**Comment by The1nstructor** [comment]
I can no longer confirm this bug. due to this fact and the age of the creation of this bug report. It will hereby by closed.
