### ISSUE TITLE
random failed to retrieve at start

### ISSUE THREAD

**Issue by helicality** [fapinstructor/fapinstructor#60]
When starting, Tumblrs will randomly fail to retrieve. Both default list and when I've changed or added some. Windows 10 with Chrome or Edge. Retrying same configuration sometimes gets all, sometimes fails to retrieve different ones.
Any way to make this work more consistently?

**Comment by The1nstructor** [comment]
Please provide your specific game setup received by pressing the __GENERATE LINK__ button and paste it here. Please also make sure that the **Editable?** switch is on, like in the picture below.

![screenshot 2018-09-02 12 27 18](https://user-images.githubusercontent.com/40101021/44954972-c276b400-aeab-11e8-9068-124e534360c4.png)

This will help us pinpoint the issue. Thank you!

**Comment by The1nstructor** [comment]
But a first guess would be #16 

to solve this just open one of the tumblrs in a second tab in your browser and agree to the shown privacy message from tumblr.

afterwards start your game. It should work now.

**Comment by helicality** [comment]
Here's the link, but as I mentioned it can happen with the default list. I tried opening the tumblrs in different tabs before starting, and it didn't make a difference. I am in fact logged into tumblr as well.
fapinstructor.com/game/eyJ2ZXJzaW9uIjoyLCJ0dW1ibHJJZCI6ImZhcHN0ZXJnaWZzLGFsbGNvd2dpcmwsYWxsY3VubmlsaW5ndXMsYWxsbWFzdHVyYmF0aW9uLGFsbGJvb2JzLGFsbGRvZ2d5IiwiZmFpbGVkSWRzIjpbImFsbG1hc3R1cmJhdGlvbiIsImFsbGNvd2dpcmwiXSwicmVkZGl0SWQiOiI2MGZwc3Bvcm4sIHBvcm5pbmFtaW51dGUiLCJnaWZzIjp0cnVlLCJwaWN0dXJlcyI6dHJ1ZSwidmlkZW9zIjp0cnVlLCJzbGlkZUR1cmF0aW9uIjoxMCwiZW5hYmxlVm9pY2UiOnRydWUsImVuYWJsZU1vYW5zIjp0cnVlLCJ2aWRlb011dGVkIjpmYWxzZSwiZmluYWxPcmdhc21BbGxvd2VkIjp0cnVlLCJhbGxvd2VkUHJvYmFiaWxpdHkiOjEwMCwiZmluYWxPcmdhc21EZW5pZWQiOmZhbHNlLCJkZW5pZWRQcm9iYWJpbGl0eSI6MCwiZmluYWxPcmdhc21SdWluZWQiOmZhbHNlLCJydWluZWRQcm9iYWJpbGl0eSI6MCwiZmluYWxPcmdhc21SYW5kb20iOmZhbHNlLCJtaW5pbXVtR2FtZVRpbWUiOjUsIm1heGltdW1HYW1lVGltZSI6IjEwIiwibWluaW11bUVkZ2VzIjowLCJtaW5pbXVtUnVpbmVkT3JnYXNtcyI6MCwibWF4aW11bVJ1aW5lZE9yZ2FzbXMiOjAsIm1heGltdW1Pcmdhc21zIjoxLCJwb3N0T3JnYXNtVG9ydHVyZSI6dHJ1ZSwicG9zdE9yZ2FzbVRvcnR1cmVNaW5pbXVtVGltZSI6MTAsInBvc3RPcmdhc21Ub3J0dXJlTWF4aW11bVRpbWUiOiIzMCIsImFkdmFuY2VkRWRnaW5nIjp0cnVlLCJhZHZhbmNlZE9yZ2FzbSI6dHJ1ZSwiZWRnZUNvb2xkb3duIjo1LCJlZGdlRnJlcXVlbmN5IjowLCJydWluQ29vbGRvd24iOjIwLCJzbG93ZXN0U3Ryb2tlU3BlZWQiOjAuMjUsImZhc3Rlc3RTdHJva2VTcGVlZCI6IjIiLCJpbml0aWFsR3JpcFN0cmVuZ3RoIjozLCJkZWZhdWx0U3Ryb2tlU3R5bGUiOjAsImFjdGlvbkZyZXF1ZW5jeSI6NSwidGFza3MiOnsiZG91YmxlU3Ryb2tlcyI6dHJ1ZSwiaGFsdmVkU3Ryb2tlcyI6dHJ1ZSwidGVhc2luZ1N0cm9rZXMiOnRydWUsImFjY2VsZXJhdGlvbkN5Y2xlcyI6dHJ1ZSwicmFuZG9tQmVhdCI6dHJ1ZSwicmFuZG9tU3Ryb2tlU3BlZWQiOnRydWUsInJlZExpZ2h0R3JlZW5MaWdodCI6dHJ1ZSwiY2x1c3RlclN0cm9rZXMiOnRydWUsImRvbWluYW50Ijp0cnVlLCJub25kb21pbmFudCI6dHJ1ZSwiaGVhZE9ubHkiOnRydWUsInNoYWZ0T25seSI6dHJ1ZSwib3ZlcmhhbmRHcmlwIjp0cnVlLCJib3RoSGFuZHMiOnRydWUsImhhbmRzT2ZmIjp0cnVlLCJncmlwQWRqdXN0bWVudHMiOnRydWUsImJpbmRDb2NrQmFsbHMiOnRydWUsInJ1YmJlckJhbmRzIjp0cnVlLCJiYWxsU2xhcHMiOnRydWUsInNxdWVlemVCYWxscyI6dHJ1ZSwiaGVhZFBhbG1pbmciOnRydWUsImljeUhvdCI6dHJ1ZSwidG9vdGhwYXN0ZSI6dHJ1ZSwiYnJlYXRoUGxheSI6dHJ1ZSwic2NyYXRjaGluZyI6dHJ1ZSwiZmxpY2tpbmciOnRydWUsImNidEljZSI6dHJ1ZSwicHJlY3VtIjp0cnVlLCJidXR0cGx1ZyI6dHJ1ZSwicnViTmlwcGxlcyI6dHJ1ZSwiY2xvdGhlc3BpbnMiOnRydWUsIm5pcHBsZXNBbmRTdHJva2UiOnRydWUsInBpY2tZb3VyUG9pc29uIjp0cnVlfSwiYWxsb3dDb25maWdFZGl0Ijp0cnVlfQ

**Comment by The1nstructor** [comment]
Thank you for your patience, 

I will look into this ASAP!

**Comment by The1nstructor** [comment]
I am actually not so much into this, maybe @LenAnderson from #83 can say more about that issue ._.

**Comment by LenAnderson** [comment]
I can't seem to reproduce this.

If I don't open tumblr beforehand I get the consent redirects. After opening tumblr (logged in) it doesn't matter how many times I refresh and start over, all of the calls to the tumblr api work without a hitch.

@helicality Could you please check what happens to the tumblr requests when it's not working?
Before starting the game open the developer tools (F12 in Chrome). Switch to the Network tab. Then press the game's Start button and see what turns up.

![imgur](https://i.imgur.com/Z10BKMr.png)

**Comment by The1nstructor** [comment]
#89 makes this debate useless.
