### ISSUE TITLE
Not working with just images

### ISSUE THREAD

**Issue by DedSecLives** [fapinstructor/fapinstructor#79]
When using subreddits as the only source, and disabling videos and gifs, it doesn't show any images. It just lets gifs and videos through despite them being disabled.

[Here's a test link](https://fapinstructor.com/game/eyJ2ZXJzaW9uIjoyLCJ0dW1ibHJJZCI6IiIsImZhaWxlZElkcyI6W10sInJlZGRpdElkIjoibnNmdywgbnNmdzIiLCJnaWZzIjpmYWxzZSwicGljdHVyZXMiOnRydWUsInZpZGVvcyI6ZmFsc2UsInNsaWRlRHVyYXRpb24iOjEwLCJlbmFibGVWb2ljZSI6dHJ1ZSwiZW5hYmxlTW9hbnMiOnRydWUsInZpZGVvTXV0ZWQiOmZhbHNlLCJmaW5hbE9yZ2FzbUFsbG93ZWQiOnRydWUsImFsbG93ZWRQcm9iYWJpbGl0eSI6MTAwLCJmaW5hbE9yZ2FzbURlbmllZCI6ZmFsc2UsImRlbmllZFByb2JhYmlsaXR5IjowLCJmaW5hbE9yZ2FzbVJ1aW5lZCI6ZmFsc2UsInJ1aW5lZFByb2JhYmlsaXR5IjowLCJmaW5hbE9yZ2FzbVJhbmRvbSI6ZmFsc2UsIm1pbmltdW1HYW1lVGltZSI6NSwibWF4aW11bUdhbWVUaW1lIjoyMCwibWluaW11bUVkZ2VzIjowLCJtaW5pbXVtUnVpbmVkT3JnYXNtcyI6MCwibWF4aW11bVJ1aW5lZE9yZ2FzbXMiOjAsIm1heGltdW1Pcmdhc21zIjoxLCJwb3N0T3JnYXNtVG9ydHVyZSI6ZmFsc2UsInBvc3RPcmdhc21Ub3J0dXJlTWluaW11bVRpbWUiOjEwLCJwb3N0T3JnYXNtVG9ydHVyZU1heGltdW1UaW1lIjo5MCwiYWR2YW5jZWRFZGdpbmciOnRydWUsImFkdmFuY2VkT3JnYXNtIjp0cnVlLCJlZGdlQ29vbGRvd24iOjEwLCJlZGdlRnJlcXVlbmN5IjowLCJydWluQ29vbGRvd24iOjIwLCJzbG93ZXN0U3Ryb2tlU3BlZWQiOjAuMjUsImZhc3Rlc3RTdHJva2VTcGVlZCI6NSwiaW5pdGlhbEdyaXBTdHJlbmd0aCI6MywiZGVmYXVsdFN0cm9rZVN0eWxlIjowLCJhY3Rpb25GcmVxdWVuY3kiOjUsInRhc2tzIjp7ImRvdWJsZVN0cm9rZXMiOnRydWUsImhhbHZlZFN0cm9rZXMiOnRydWUsInRlYXNpbmdTdHJva2VzIjp0cnVlLCJhY2NlbGVyYXRpb25DeWNsZXMiOnRydWUsInJhbmRvbUJlYXQiOnRydWUsInJhbmRvbVN0cm9rZVNwZWVkIjp0cnVlLCJyZWRMaWdodEdyZWVuTGlnaHQiOnRydWUsImNsdXN0ZXJTdHJva2VzIjp0cnVlLCJkb21pbmFudCI6dHJ1ZSwibm9uZG9taW5hbnQiOnRydWUsImhlYWRPbmx5Ijp0cnVlLCJzaGFmdE9ubHkiOnRydWUsIm92ZXJoYW5kR3JpcCI6dHJ1ZSwiYm90aEhhbmRzIjp0cnVlLCJoYW5kc09mZiI6dHJ1ZSwiZ3JpcEFkanVzdG1lbnRzIjp0cnVlLCJiaW5kQ29ja0JhbGxzIjp0cnVlLCJydWJiZXJCYW5kcyI6dHJ1ZSwiYmFsbFNsYXBzIjp0cnVlLCJzcXVlZXplQmFsbHMiOnRydWUsImhlYWRQYWxtaW5nIjp0cnVlLCJpY3lIb3QiOnRydWUsInRvb3RocGFzdGUiOnRydWUsImJyZWF0aFBsYXkiOnRydWUsInNjcmF0Y2hpbmciOnRydWUsImZsaWNraW5nIjp0cnVlLCJjYnRJY2UiOnRydWUsInByZWN1bSI6dHJ1ZSwiYnV0dHBsdWciOnRydWUsInJ1Yk5pcHBsZXMiOnRydWUsImNsb3RoZXNwaW5zIjp0cnVlLCJuaXBwbGVzQW5kU3Ryb2tlIjp0cnVlLCJwaWNrWW91clBvaXNvbiI6dHJ1ZX0sImFsbG93Q29uZmlnRWRpdCI6dHJ1ZX0)

**Comment by The1nstructor** [comment]
Thank you for your feedback! 

I hope somebody of the other devs will be able to look into this, as I am not that much into the games displaying engine.

But anyway thanks for the information.

**Comment by DedSecLives** [comment]
Looking at [/src/api/fetchRedditPics.js](https://github.com/fapinstructor/fapinstructor/blob/master/src/api/fetchRedditPics.js) it seems there's only filtering for gfycat and erome. I'd attempt a fork but I really don't know much about JS. 

I might try fudging something together.

**Comment by The1nstructor** [comment]
If you got spare time, and would like to participate, go ahead! Just please make a pull request very early so other devs may help you, share opinion etc.

I would appreciate your contribution very much. 😊

**Comment by The1nstructor** [comment]
Please note that work is done about this topic in #83

**Comment by The1nstructor** [comment]
Also #120 and #98 close this did improve this a lot. So this problem won’t exist any more.
