### ISSUE TITLE
tumblr doesn't load

### ISSUE THREAD

**Issue by GreATMaN80** [fapinstructor/fapinstructor#85]
**Describe the bug**
when i want to load my fapinstructor, only a few tumblr load (4 or 5) while there are many more requested. Is this normal? am I too much?

**To Reproduce**
This is my setting:
fapinstructor.com/game/eyJ2ZXJzaW9uIjoyLCJ0dW1ibHJJZCI6ImNlbGVianVuY3Rpb24sIGx1eHVyeS10ZWxseS10b3R0eSwgaG90LWhvdHRlci1rYXR5cGVycnksIGVtbWF3YXRzb25zbGVnZ2dzLCB0dXJuZWQtb24tYnktYWxleGFuZHJhLWRhZGRhcmlvLCB0dXJuZWQtb24tYnktaGF5ZGVuLXBhbmV0dGllcmUsIGltLXR1cm5lZC1vbi1ieS1qZXNzaWNhLWFsYmEsIGFzaGx5bm4tYnJvb2tlcy15YXJkLCBlbW1hLXdhdHNvbi1zaHJpbmUsIHRoZS1yZWQtZm94LWZpbGVzLCB3YXRzb25sb3ZlLCBsaXR0bGVjYXByaWNlbG92ZXIsIGFjdGVjdXRoYmVydCwgcmVkZGxyLWdlbnRsZW1hbmJvbmVycywga2F0ZXJpbmEta296bG92YTksIGZ1Y2t5ZWFoYnJ5Y2ksIGFsaXNvbmJyaWVpc3RoZW9uZS1ibG9nLCBsaXR0bGVjYXByaWNlcGljeCwgYnJ5Y2lzaWVnLCBob3QtaG90dGVyLWplbm5pZmVybGF3cmVuY2UsIHNpbGt5aG90YnJ5Y2ksIGdvZGRlc3NlbXdhdHNvbiwgZi15ZWFoYWxpc29uYnJpZSwgcGJkaWxsaW9uaGFycGVyLCBzZXh5aGF5ZGVucGFuZXR0aWVyZSwgd2F0c29udGl0cywgc2V4eXNjYXJsZXR0am9oYW5zc29uLCBldmVyeXRoaW5ndXB0b24sIGJyeWNpbnVkZXBpY3MsIGlubGVzYmlhbndpdGhqZW5uaWZlcmxhd3JlbmNlLCBob3RhbGlzb25icmllLCBteXNvdWxmb3Jhbm5hLCBob2x5c2hpeml0c2VtbWF3YXRzb24sIGZ1Y2t5ZWFoYWxsaWVzaW4sIGhvdC1ob3R0ZXItbWljaGVsbGV0cmFjaHRlbmJlcmcsIHBlcnJ5Ym9vYnMsIGhvdC1ob3R0ZXItc2NhcmxldHRqb2hhbnNzb24iLCJmYWlsZWRJZHMiOltdLCJyZWRkaXRJZCI6IiIsImdpZnMiOnRydWUsInBpY3R1cmVzIjp0cnVlLCJ2aWRlb3MiOnRydWUsInNsaWRlRHVyYXRpb24iOjMsImVuYWJsZVZvaWNlIjp0cnVlLCJlbmFibGVNb2FucyI6dHJ1ZSwidmlkZW9NdXRlZCI6dHJ1ZSwiZmluYWxPcmdhc21BbGxvd2VkIjp0cnVlLCJhbGxvd2VkUHJvYmFiaWxpdHkiOjEwMCwiZmluYWxPcmdhc21EZW5pZWQiOmZhbHNlLCJkZW5pZWRQcm9iYWJpbGl0eSI6MCwiZmluYWxPcmdhc21SdWluZWQiOmZhbHNlLCJydWluZWRQcm9iYWJpbGl0eSI6MCwiZmluYWxPcmdhc21SYW5kb20iOmZhbHNlLCJtaW5pbXVtR2FtZVRpbWUiOjE1LCJtYXhpbXVtR2FtZVRpbWUiOjIwLCJtaW5pbXVtRWRnZXMiOjEsIm1pbmltdW1SdWluZWRPcmdhc21zIjowLCJtYXhpbXVtUnVpbmVkT3JnYXNtcyI6MCwibWF4aW11bU9yZ2FzbXMiOjIsInBvc3RPcmdhc21Ub3J0dXJlIjp0cnVlLCJwb3N0T3JnYXNtVG9ydHVyZU1pbmltdW1UaW1lIjoxMCwicG9zdE9yZ2FzbVRvcnR1cmVNYXhpbXVtVGltZSI6OTAsImFkdmFuY2VkRWRnaW5nIjp0cnVlLCJhZHZhbmNlZE9yZ2FzbSI6dHJ1ZSwiZWRnZUNvb2xkb3duIjoxMCwiZWRnZUZyZXF1ZW5jeSI6MCwicnVpbkNvb2xkb3duIjoyMCwic2xvd2VzdFN0cm9rZVNwZWVkIjoxLCJmYXN0ZXN0U3Ryb2tlU3BlZWQiOjUsImluaXRpYWxHcmlwU3RyZW5ndGgiOjMsImRlZmF1bHRTdHJva2VTdHlsZSI6MCwiYWN0aW9uRnJlcXVlbmN5Ijo1LCJ0YXNrcyI6eyJkb3VibGVTdHJva2VzIjp0cnVlLCJoYWx2ZWRTdHJva2VzIjp0cnVlLCJ0ZWFzaW5nU3Ryb2tlcyI6dHJ1ZSwiYWNjZWxlcmF0aW9uQ3ljbGVzIjp0cnVlLCJyYW5kb21CZWF0IjpmYWxzZSwicmFuZG9tU3Ryb2tlU3BlZWQiOnRydWUsInJlZExpZ2h0R3JlZW5MaWdodCI6dHJ1ZSwiY2x1c3RlclN0cm9rZXMiOmZhbHNlLCJkb21pbmFudCI6dHJ1ZSwibm9uZG9taW5hbnQiOnRydWUsImhlYWRPbmx5Ijp0cnVlLCJzaGFmdE9ubHkiOnRydWUsIm92ZXJoYW5kR3JpcCI6dHJ1ZSwiYm90aEhhbmRzIjp0cnVlLCJoYW5kc09mZiI6dHJ1ZSwiZ3JpcEFkanVzdG1lbnRzIjp0cnVlLCJiaW5kQ29ja0JhbGxzIjpmYWxzZSwicnViYmVyQmFuZHMiOnRydWUsImJhbGxTbGFwcyI6ZmFsc2UsInNxdWVlemVCYWxscyI6dHJ1ZSwiaGVhZFBhbG1pbmciOnRydWUsImljeUhvdCI6ZmFsc2UsInRvb3RocGFzdGUiOmZhbHNlLCJicmVhdGhQbGF5Ijp0cnVlLCJzY3JhdGNoaW5nIjpmYWxzZSwiZmxpY2tpbmciOnRydWUsImNidEljZSI6ZmFsc2UsInByZWN1bSI6ZmFsc2UsImJ1dHRwbHVnIjpmYWxzZSwicnViTmlwcGxlcyI6dHJ1ZSwiY2xvdGhlc3BpbnMiOmZhbHNlLCJuaXBwbGVzQW5kU3Ryb2tlIjp0cnVlLCJwaWNrWW91clBvaXNvbiI6dHJ1ZX0sImFsbG93Q29uZmlnRWRpdCI6dHJ1ZX0

**Expected behaviour**
Just have all my contents

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: CHROME but I try on every Browser

**Comment by The1nstructor** [comment]
maybe #83 will fix this.
