### ISSUE TITLE
Tumblr bans adult content December 17

### ISSUE THREAD

**Issue by helicality** [fapinstructor/fapinstructor#89]
https://tumblr.zendesk.com/hc/en-us/articles/231885248-Sensitive-content

**Comment by LenAnderson** [comment]
Wow. I guess that means all the issues related to tumblr can be closed... Unless people are way more into fapping to kitten pictures than I thought :D

I'll try to get reddit fetching (PR #83) in a release-worthy state in time. I think support for the biggest hosters is covered so maybe I'll just leave out the rest of the list for now.

**Comment by The1nstructor** [comment]
Well we then probably should remove the Tumblr Line from the game 😕
